
filebeat:
  config:
    modules:
      path: ${path.config}/modules.d/*.yml
      reload:
        enabled: false
  inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log
  
  - type: log
    enabled: true
    paths:
      - /var/log/tomcat/*
    tags: ["catalina"]
    document_type: catalina
    fields:
      type: catalina
    fields_under_root: true
    multiline:
      pattern: '^[[:space:]]'
      negate: false
      match: after
  
  - type: log
    enabled: true
    paths:
      - /var/log/lumisportal/full/*
    tags: ["lumislog"]
    document_type: lumislogfull
    fields:
      type: lumislogfull
    fields_under_root: true
    multiline:
      pattern: '^[[:space:]]'
      negate: false
      match: after


#output.elasticsearch:
#  hosts: ["${ELASTICSEARCH_HOST}:9200"]

output:
  logstash:
    hosts: ["${LOGSTASH_HOST}:5000"]

setup: 
  template.settings:
    index.number_of_shards: 1
  kibana:
    host: "${KIBANA_HOST}:5601"
  dashboards:
    enabled: true

processors:
  - add_host_metadata: ~

monitoring.enabled: true
logging.to_files: false

filebeat.modules:
- module: apache
  access:
    enabled: true
    var.paths: ['/var/log/apache2/access_log*']
  error:
    enabled: true
    var.paths: ['/var/log/apache2/error_log*']
