filebeat: 
  #prospectors:
  #  - paths:
  #      - /var/log/lumisportal/full/logfull.log
  #    input_type: log
  #    multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  #    multiline.negate: true
  #    multiline.match: after 
  inputs:
  - type: log
    enabled: false
    paths:
      - /var/log/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

#output.elasticsearch:
#  hosts: ["${ELASTICSEARCH_HOST}:9200"]

output.logstash:
  hosts: ["${LOGSTASH_HOST}:5000"]

setup: 
  template.settings:
    index.number_of_shards: 1
  kibana.host: "${KIBANA_HOST}:5601"
  dashboards.enabled: true

processors:
  - add_host_metadata: ~

monitoring.enabled: true
logging.to_files: false

filebeat.modules:
#- module: system
#  syslog:
#    var.paths: ["/var/log/host/system.log*"]

- module: apache
  access:
    enabled: true
    var.paths: ['/var/log/apache2/access_log*']
  error:
    enabled: true
    var.paths: ['/var/log/apache2/error_log*']
