version: '3.7'
services:
  database:
    image: mysql:5.5
    command: >
        
        --max_allowed_packet=134217728
    volumes:
      - type: volume
        source: database_data
        target: /var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=87ti5ox6
      - MYSQL_DATABASE=lumisportal
      - MYSQL_USER=lumisportal
      - MYSQL_PASSWORD=lumisportal  
    networks:
      - lumisxp704
    ports: 
      - 3306:3306
    healthcheck:
        test: "/usr/bin/mysql --user=lumisportal --password=lumisportal --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10


  lumisxp:
    image: jeduoliveira/lumisxp:7.0.4.131220
    environment:
      - TOMCAT_AJP_MAX_THREADS=20
      - TOMCAT_HTTP_MAX_THREADS=5
      - TOMCAT_HEAP=512M
      - LUMIS_DB_HOST=database
      - LUMIS_DB_PORT=3306
      - LUMIS_DB_USER=lumisportal
      - LUMIS_DB_PASSWORD=lumisportal
      - LUMIS_DB_NAME=lumisportal
      - LUMIS_DB_MINIMUM_IDLE=10
      - LUMIS_DB_MAXIMUM_POOL_SIZE=100
      - LUMIS_SERVER_ID=lumisxp
      
      - WEB_ROOT_PATH=/usr/local/htdocs
    volumes:
      
      - type: volume
        source: lumis_data
        target: /usr/local/lumisportal/lumisdata/data
      - type: volume
        source: lumis_shared
        target: /usr/local/lumisportal/lumisdata/shared
      
    depends_on:
       - database  
    ports: 
      - 8080:8080    
      
    links:
      - database
     
    networks:
      - lumisxp704
    healthcheck:
      test: curl -sS http://lumisxp:8080/login.jsp || exit 1
      interval: 60s
      timeout: 10s
      retries: 50

  
      
volumes:
  database_data:
 
  lumis_data:
  lumis_shared: 
 
networks:
  lumisxp704: