version: '3.7'
services:
  database:
    image: mysql:8.0-oracle
    restart: always
    command: >
        --default-authentication-plugin=mysql_native_password 
        --max_allowed_packet=134217728
        --log_bin_trust_function_creators=1
    volumes:
      - type: volume
        source: database_data
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=lum1sPassw0rd
      - MYSQL_PASSWORD=lum1sPassw0rd
      - MYSQL_DATABASE=lumisportal
      - MYSQL_USER=lumisportal
      - TZ=America/Sao_Paulo
    ports:
      - 3306:3306
    networks:
      - lumis

  elasticsearch:
    image: public.ecr.aws/p7k8w7p7/elasticsearch:7.17.17
    restart: always
    environment:
      - node.name=node1
      - cluster.name=lumisportal  
      - discovery.type=single-node  
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
      - "action.auto_create_index=-lumisportal-*,+*"
      - "search.max_buckets=30000"
      - TZ=America/Sao_Paulo
    ulimits:
      nproc: 262144
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    cap_add:
      - ALL
    volumes:
      - type: volume
        source: elastic_data
        target: /usr/share/elasticsearch/data
      - type: volume
        source: lumis_analysis
        target: /usr/share/elasticsearch/config/lumis-analysis
    networks:
      - lumis
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 50
  
  lumisxp:
    image: public.ecr.aws/p7k8w7p7/lumisxp:16.0.0.230707-FreeVersion
    restart: always
    environment:
      - LUMIS_DB_PASSWORD=lum1sPassw0rd
      - LUMIS_VERSION=16.0.0.230707
      - TOMCAT_AJP_MAX_THREADS=20
      - TOMCAT_HTTP_MAX_THREADS=5
      - TOMCAT_HEAP=512M
      - LUMIS_DB_HOST=database
      - LUMIS_DB_PORT=3306
      - LUMIS_DB_USER=lumisportal
      - LUMIS_DB_NAME=lumisportal
      - LUMIS_DB_MINIMUM_IDLE=10
      - LUMIS_DB_MAXIMUM_POOL_SIZE=100
      - LUMIS_SERVER_ID=lumisxp
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_CLUSTER_NAME=lumisportal  
      - WEB_ROOT_PATH=/usr/local/htdocs
      - TZ=America/Sao_Paulo
    volumes:
      - type: volume 
        source: lumis_analysis
        target: /usr/share/elasticsearch/config/lumis-analysis
      - type: volume
        source: lumis_data
        target: /usr/local/lumisportal/lumisdata/data
      - type: volume
        source: lumis_shared
        target: /usr/local/lumisportal/lumisdata/shared
      - type: volume
        source: lumis_htdocs
        target: /usr/local/htdocs
    depends_on:
       - database      
       - elasticsearch
    links:
      - database
      - elasticsearch
    networks:
      - lumis
    ports: 
      - 8080:8080
    healthcheck:
      test: curl -sS http://lumisxp:8080/login.jsp || exit 1
      interval: 60s
      timeout: 10s
      retries: 50
    
  apache:
    image: public.ecr.aws/p7k8w7p7/apache:2.4
    restart: always
    depends_on:
      - lumisxp     
    ports: 
      - 80:80    
    links:
      - lumisxp
    networks:
      - lumis
    environment:
      - TZ=America/Sao_Paulo
    volumes:
    - type: volume 
      source: lumis_htdocs
      target: /usr/local/apache2/htdocs

volumes:
  database_data:
  elastic_data:
  lumis_analysis:
  lumis_data:
  lumis_shared: 
  lumis_htdocs:

networks:
  lumis: