version: '3.7'
services:
  database:
    image: mysql:5.7
    command: >
        --default-authentication-plugin=mysql_native_password 
        --max_allowed_packet=134217728
    volumes:
      - type: volume
        source: database_data
        target: /var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=87ti5ox6
      - MYSQL_DATABASE=lumisportal
      - MYSQL_USER=lumisportal
      - MYSQL_PASSWORD=lumisportal  
    networks:
      - lumisxp
    ports: 
      - 3306:3306
    healthcheck:
        test: "/usr/bin/mysql --user=lumisportal --password=lumisportal --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10

  elasticsearch:
    image: jeduoliveira/lumisxp-elasticsearch:7.1.1
    environment:
      - node.name=node1
      - cluster.name=lumisportal      
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
      - "action.auto_create_index=-lumisportal-*,+*"
      - "search.max_buckets=30000"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    volumes:
      - type: volume
        source: elastic_data
        target: /usr/share/elasticsearch/data
      - type: volume
        source: lumis_analysis
        target: /usr/share/elasticsearch/config/lumis-analysis
    networks:
      - lumisxp
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  lumisxp:
    image: jeduoliveira/lumisxp:12.1.0.191010-freeversion-centos-7-zulu-11
    environment:
      - TOMCAT_AJP_MAX_THREADS=20
      - TOMCAT_HTTP_MAX_THREADS=5
      - TOMCAT_HEAP=512M
      - LUMIS_DB_HOST=database
      - LUMIS_DB_PORT=3306
      - LUMIS_DB_USER=lumisportal
      - LUMIS_DB_PASSWORD=lumisportal
      - LUMIS_DB_NAME=lumisportal
      - LUMIS_DB_MINIMUM_IDLE=10
      - LUMIS_DB_MAXIMUM_POOL_SIZE=100
      - LUMIS_SERVER_ID=lumisxp
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_CLUSTER_NAME=lumisportal  
      - WEB_ROOT_PATH=/usr/local/htdocs
    volumes:
      - type: volume 
        source: lumis_analysis
        target: /usr/share/elasticsearch/config/lumis-analysis
      - type: volume
        source: lumis_data
        target: /usr/local/lumisportal/lumisdata/data
      - type: volume
        source: lumis_shared
        target: /usr/local/lumisportal/lumisdata/shared
      - type: volume
        source: lumis_htdocs
        target: /usr/local/htdocs
    depends_on:
       - database      
       - elasticsearch
    links:
      - database
      - elasticsearch
    networks:
      - lumisxp
    healthcheck:
      test: curl -sS http://lumisxp:8080/login.jsp || exit 1
      interval: 60s
      timeout: 10s
      retries: 50

  httpd:
    image: jeduoliveira/httpd
    depends_on:
      - lumisxp     
    ports: 
      - "80:80"    
    links:
      - lumisxp
    networks:
      - lumisxp
    volumes:
    - type: volume 
      source: lumis_htdocs
      target: /usr/local/apache2/htdocs
      
volumes:
  database_data:
  elastic_data:
  lumis_analysis:
  lumis_data:
  lumis_shared: 
  lumis_htdocs:

networks:
  lumisxp: