version: '3.7'
services:
  elasticsearch:
    image: jeduoliveira/elasticsearch:7.1.1
    environment:
      - node.name=node1
      - cluster.name=lumisportal
      - cluster.initial_master_nodes=node1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=0.0.0.0
      - "action.auto_create_index= -lumisportal-*,+*"  
      - xpack.monitoring.collection.enabled=true    
    volumes:
      - type: volume
        source: elastic_data
        target: /usr/share/elasticsearch/data
      - type: volume
        source: lumis_analysis
        target: /usr/share/elasticsearch/config/lumis-analysis        
      - type: bind
        source: /etc/localtime
        target: /etc/localtime      
    ports: ['9200:9200', '9300:9300']
    networks: ['monitoring']
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    healthcheck:            
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
      interval: 30s
      timeout: 30s
      retries: 10
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1 
    ports: ['5601:5601']
    depends_on: ['elasticsearch']        
    networks: ['monitoring']
    volumes:      
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
    healthcheck:
      test: curl https://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 10

  metricbeat:
    build: 
      context: docker/metricbeat
      args:
        ELK_VERSION: $ELK_VERSION
    command: ["--strict.perms=false", "-system.hostfs=/hostfs", "-e"]
    user: root
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-node1}
      - KIBANA_HOST=${KIBANA_HOST:-node1}
    volumes:
      - type: bind
        source: /proc
        target: /hostfs/proc
      - type: bind
        source: /sys/fs/cgroup
        target: /hostfs/sys/fs/cgroup
      - type: bind
        source: /
        target: /hostfs
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock      
      - type: volume
        source: metricbeat
        target: /usr/share/metricbeat/data    
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
    depends_on: ['kibana', 'elasticsearch']
    networks: ['monitoring']  
    restart: on-failure
    healthcheck:
      test: metricbeat test config
      interval: 30s
      timeout: 15s
  
  filebeat:
    build: 
      context: docker/filebeat
      args:
        ELK_VERSION: $ELK_VERSION
    command: ["--strict.perms=false", "-e"]
    user: root
    networks: ['monitoring'] 
    restart: on-failure     
    #links: ['logstash']
    volumes:
      - type: volume
        source: filebeat
        target: /usr/share/filebeat/data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock 
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
      - type: bind
        source: ./logs/apache2
        target: /var/log/apache2
      - type: bind
        source: ./logs/lumisportal
        target: /var/log/lumisportal  
      - type: bind
        source: ./logs/mysql
        target: /var/log/mysql
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
    environment:
      - LOGSTASH_HOST=${LOGSTASH_HOST:-node1}
      - KIBANA_HOST=${KIBANA_HOST:-node1}      
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-node1}      

  #logstash:
  #  build:
  #    context: docker/logstash
  #    args:
  #      ELK_VERSION: $ELK_VERSION
  #  command: [ "-e"]
  #  ports:
  #    - "5000:5000/tcp"
  #    - "5000:5000/udp"
  #    - "9600:9600"
  #  environment:
  #    - LS_JAVA_OPTS=-Xmx256m -Xms256m
  #    - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-node1}    
  #  networks: ['monitoring'] 
  #  depends_on: ['kibana', 'elasticsearch']
  #  volumes:      
  #    - type: bind
  #      source: /etc/localtime
  #      target: /etc/localtime

  apm-server:
    build: 
      context: docker/apm-server
      args:
        ELK_VERSION: $ELK_VERSION
    ports: ['8200:8200', '8201:8200']
    environment:
      - apm-server.host=0.0.0.0
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-node1}
      - KIBANA_HOST=${KIBANA_HOST:-node1}  
    networks: ['monitoring']
    depends_on: ['kibana', 'elasticsearch']    
    links: ['elasticsearch']
    volumes:      
      - type: bind
        source: /etc/localtime
        target: /etc/localtime

  db:
    image: mysql:5.7    
    environment: 
      - MYSQL_ROOT_PASSWORD=87ti5ox6
      - MYSQL_DATABASE=lumisportal
      - MYSQL_USER=lumisportal
      - MYSQL_PASSWORD=lumisportal
    volumes:
      - type: volume
        source: database_data
        target: /var/lib/mysql
      - type: bind
        source: ./logs/mysql
        target: /var/log/mysql/
      - type: bind
        source: /etc/localtime
        target: /etc/localtime

    ports: ['3306:3306']
    networks: ['monitoring']  
    healthcheck:
        test: "/usr/bin/mysql --user=lumisportal --password=lumisportal --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10    

  lumisxp:    
    build: ./docker/lumisxp
    environment:
      - TOMCAT_AJP_MAX_THREADS=50
      - TOMCAT_HTTP_MAX_THREADS=10
      - TOMCAT_HEAP=512M
      - LUMIS_DB_HOST=db
      - LUMIS_DB_PORT=3306
      - LUMIS_DB_USER=lumisportal
      - LUMIS_DB_PASSWORD=lumisportal
      - LUMIS_DB_NAME=lumisportal
      - LUMIS_DB_MINIMUM_IDLE=10
      - LUMIS_DB_MAXIMUM_POOL_SIZE=100
      - LUMIS_SERVER_ID=lumisxp
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_CLUSTER_NAME=lumisportal  
      - WEB_ROOT_PATH=/usr/local/htdocs
    volumes:
      - type: volume 
        source: lumis_analysis
        target: /usr/share/elasticsearch/config/lumis-analysis
      - type: volume
        source: lumis_data
        target: /usr/local/lumisportal/lumisdata/data
      - type: volume
        source: lumis_shared
        target: /usr/local/lumisportal/lumisdata/shared
      - type: volume
        source: lumis_htdocs
        target: /usr/local/htdocs
      - type: bind
        source: ./logs/lumisportal
        target: /usr/local/lumisportal/lumisdata/log
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
    depends_on: [ 'elasticsearch']
    networks: ['monitoring']
    ports: ['8080:8080', '8009:8009']
    links: ['apm-server', 'db']
    healthcheck:
      test: curl -sS http://localhost:8080/login.jsp || exit 1
      interval: 60s
      timeout: 10s
      retries: 50

  apache:
    build: ./docker/apache
    depends_on: ['lumisxp']
    networks: ['monitoring']   
    ports: ['80:80']
    volumes:
    - type: volume 
      source: lumis_htdocs
      target: /usr/local/apache2/htdocs
    - type: bind
      source: ./logs/apache2
      target: /usr/local/apache2/logs
    - type: bind
      source: /etc/localtime
      target: /etc/localtime

volumes:
  database_data:
  elastic_data:
  metricbeat:
  filebeat:
  lumis_analysis:
  lumis_data:
  lumis_shared: 
  lumis_htdocs:
  
networks:
  monitoring:
    