metricbeat.modules:
  

#------------------------------- System Module -------------------------------

- module: system
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory
- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
- module: system
  period: 15m
  metricsets:
    - uptime

#------------------------------- Docker Module -------------------------------

- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

#------------------------------- MySQL Module -------------------------------

- module: mysql
  enabled: true
  metricsets: ["status"]
  period: 5s
  hosts: ["tcp(db:3306)/"]
  username: lumisportal
  password: lumisportal

#------------------------------- Apache Module -------------------------------

- module: apache
  metricsets:
    - status
  period: 10s
  hosts: ["http://apache"]



  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

setup.dashboards.enabled: true

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~