metricbeat.modules:
  

#------------------------------- System Module -------------------------------

- module: system
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory
- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
- module: system
  period: 15m
  metricsets:
    - uptime

#------------------------------- Docker Module -------------------------------

- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

#------------------------------- MySQL Module -------------------------------

- module: mysql
  enabled: true
  metricsets: ["status"]
  period: 5s
  hosts: ["tcp(db:3306)/"]
  username: lumisportal
  password: lumisportal

#------------------------------- Apache Module -------------------------------

- module: apache
  metricsets:
    - status
  period: 10s
  hosts: ["http://apache"]


  #------------------------------- Apache Module -------------------------------

- module: jolokia
  metricsets: ["jmx"]
  period: 30s
  hosts: ["lumisxp:8778"]
  namespace: "metrics"
  path: "/jolokia/?ignoreErrors=true&canonicalNaming=false"
  #username: "monitor"
  #password: "secret"
  jmx.mappings:
    - mbean: 'java.lang:type=Memory'
      attributes:
        - attr: HeapMemoryUsage
          field: memory.heap_usage
    - mbean: 'java.lang:type=Threading'
      attributes:
        - attr: ThreadCount
          field: threading.thread_count
    - mbean: 'java.lang:type=OperatingSystem'
      attributes:
        - attr: SystemCpuLoad
          field: system.system_cpu_load
        - attr: SystemLoadAverage
          field: system.system_load_average
        - attr: OpenFileDescriptorCount
          field: system.opened_file_descriptors
    - mbean: 'Catalina:type=ThreadPool,name="ajp-nio-8009"'
      attributes:
        - attr: currentThreadCount
          field: threads.current_threads_count
        - attr: currentThreadsBusy
          field: threads.current_threads_busy
    - mbean: 'com.zaxxer.hikari:type=Pool (HikariPool-1)'
      attributes:
        - attr: TotalConnections
          field: pool.total_connections
        - attr: ActiveConnections
          field: pool.active_connections
  jmx.application:
  jmx.instance:
  fields:
    type: lumisxp-jmx
  fields_under_root: true

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}:9200"]

setup.kibana:
  host: "${KIBANA_HOST}:5601"

setup.dashboards:
  enabled: true

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~