name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    #- name: Trivy Scan - High and Critical Severity
    #  uses: aquasecurity/trivy-action@0.0.7
    #  with:
    #    # image reference
    #    image-ref: jeduoliveira/lumisxp:14.1.0.210906
    #    # exit code when vulnerabilities were found
    #    exit-code: 1
    #    # severities of vulnerabilities to be displayed
    #    severity: HIGH,CRITICAL

    - name: Start containers
      run: docker-compose  up -d

    - name: Sleep for 300 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '300s'

    - name: View log lumisxp
      run: docker-compose logs lumisxp 

    - name: Test
      run: docker run --network container:httpd appropriate/curl -L --retry 10 --retry-connrefused http://localhost/

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down